---
dist: xenial
language: python
python: 3.7
services: docker

install:
  - pip install --upgrade -r requirements-test.txt
script:
  - pre-commit run --all-files
  - docker-compose up
  - test -f assessment-data-import.zip
