---
name: release

on:
  release:
    types: [prereleased, released]

env:
  ASSET_NAME: assessment-data-import.zip
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Store installed Python version
        run: |
          echo "::set-env name=PY_VERSION::"\
          "$(python -c "import platform;print(platform.python_version())")"
      - name: Cache lambda building environments
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "release-${{ runner.os }}-py${{ env.PY_VERSION }}-\
            ${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            release-${{ runner.os }}-py${{ env.PY_VERSION }}-
            release-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install --upgrade --requirement requirements.txt
      - name: Build environment
        run: docker-compose build
      - name: Generate lambda zip
        run: docker-compose up
      - name: Upload lambda zip as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
